### ISSUE TITLE
Build with Wireshark 3.0.6 failed

### ISSUE THREAD

**Issue by joshiste** [ReactiveSocket/rsocket-wireshark#6]
As the README.md doesn't tell which wireshark version to use i've tried to build against the `wireshark-3.0.6` tag which results in an error:

```
CMake Error at plugins/rsocket/CMakeLists.txt:50 (register_dissector_files):
  Unknown CMake command "register_dissector_files".
```

**Comment by joshiste** [comment]
Just read that you tested against 2.2.5  - so I've switched to wireshark-2.4.15. It works.

**Comment by fjacobs** [comment]
@OlegDokuka This issue is fixed with: https://github.com/rsocket/rsocket-wireshark/pull/5
